name: flutter_pos_new
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  connectivity_plus: ^6.1.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  #flutter_inappwebview: ^5.8.0
  flutter_downloader: ^1.11.7
  fluttertoast: ^8.2.8
  get_storage: ^2.1.1
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  just_audio: ^0.9.41
  pdf: ^3.11.1
  provider: ^6.1.2
  share_plus: ^10.1.1
  printing:
  path_provider: ^2.1.5
  whatsapp_share: ^2.0.2
  flutter_barcode_scanner: 
   git:
    url: https://github.com/irawanmurjayanto/barcode_modi2.git     
  audioplayers: ^6.1.0
  currency_text_input_formatter: ^2.2.6
  qr_flutter: ^4.1.0
  print_bluetooth_thermal: ^1.1.4
  flutter_esc_pos_utils: ^1.0.1
  image: ^4.3.0
  permission_handler: ^11.3.1
  flutter_inappwebview: ^6.1.5
  carousel_slider: ^5.0.0
  flutter_slidable: ^3.1.1
  flutter_onboarding_slider: ^1.0.11
  #webview_flutter_web: ^0.2.3+4
  #webview_flutter_web: ^0.2.3+4
  #url_launcher: ^6.3.1#




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/
    - assets/logo/
 

